n1 = int(input('Um valor: '))
n2 = int(input('Outro valor: '))
print('A soma entre eles é: {}'.format(n1+n2), end=' ')
print('A diferença entre eles é: {}'.format(n1-n2))
print('O produto entre eles é: {}'.format(n1*n2))
print('A divisão entre eles é: {:.2f}'.format(n1/n2))
print('A potência entre eles é: {}'.format(n1**n2))
print('A divisão inteira entre eles é: {}'.format(n1//n2))
print('O resto da divisão \n entre eles é: {}'.format(n1 % n2))
